version: '3'
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./gestao-processos-web:/usr/src/gestao-processos-web
    container_name: gestao-processos_nginx
    ports:
      - "80:80"
    networks:
      - gestao-processos_network
    depends_on:
      - "serverapi1"
      - "serverapi2"
      - "serverapi3"
  node:
    image: node:alpine
    volumes:
      - ./gestao-processos-web:/usr/src/gestao-processos-web
    working_dir: /usr/src/gestao-processos-web
    command: /bin/sh -c "npm install && npm run build"
    container_name: gestao-processos_node
    networks:
      - gestao-processos_network
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: gestao-processos
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    container_name: gestao-processos_postgres
    networks:
      - gestao-processos_network
  serverapi1:
    build:
      dockerfile: ./gestao-processos-api/Dockerfile
      context: .
    container_name: gestao-processos_service-1
    ports:
      - "8080"
    networks:
      - gestao-processos_network
    depends_on:
      - "postgres"
  serverapi2:
    build:
      dockerfile: ./gestao-processos-api/Dockerfile
      context: .
    container_name: gestao-processos_service-2
    ports:
      - "8080"
    networks:
      - gestao-processos_network
    depends_on:
      - "postgres"
  serverapi3:
    build:
      dockerfile: ./gestao-processos-api/Dockerfile
      context: .
    container_name: gestao-processos_service-3
    ports:
      - "8080"
    networks:
      - gestao-processos_network
    depends_on:
      - "postgres"
networks:
  gestao-processos_network: