version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./gestao-processos-web:/usr/src/gestao-processos-web
    container_name: gestao-processos_nginx
    ports:
      - "8070:80"
    networks:
      - gestao-processos_network
    depends_on:
      - "serverapi"
  node:
    image: node
    volumes:
      - ./gestao-processos-web:/usr/src/gestao-processos-web
    working_dir: /usr/src/gestao-processos-web
    command: bash -c "npm install && npm run build"
    container_name: gestao-processos_node
    networks:
      - gestao-processos_network
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: gestao-processos
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    container_name: gestao-processos_postgres
    networks:
      - gestao-processos_network
  serverapi:
    image: gradle
    volumes:
      - ./gestao-processos-api:/usr/src/gestao-processos-api
    working_dir: /usr/src/gestao-processos-api
    entrypoint: gradle bootRun
    container_name: gestao-processos_service
    ports:
      - "8080"
    networks:
      - gestao-processos_network
    depends_on:
      - "postgres"
networks:
  gestao-processos_network:
    driver: bridge